{% set version = "0.4.3" %}


package:
  name: pytest-watcher
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-watcher/pytest_watcher-{{ version }}.tar.gz
  sha256: 0cb0e4661648c8c0ff2b2d25efa5a8e421784b9e4c60fcecbf9b7c30b2d731b3

build:
  number: 1
  noarch: python
  entry_points:
    - ptw = pytest_watcher:run
    - pytest-watcher = pytest_watcher:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry-core >=1.0.0
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0
    - watchdog >=2.0.0
    - tomli >=2.0.0

test:
  imports:
    - pytest_watcher
  commands:
    - pip check
    - ptw --help
    - pytest-watcher --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/olzhasar/pytest-watcher
  summary: Continiously runs pytest on changes in *.py files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bryanwweber
